package resources;

//Json Simple dependency: https://cliftonlabs.github.io/json-simple/target/json-simple-3.1.1.jar

public class Main {
    
    public static void main(String[] args) {

        //Run this class to autogenerated the R class
        
        ResourcesLoader resourcesLoader = new ResourcesLoader();
        resourcesLoader.loadResources();

        if(resourcesLoader.AreAllResourcesLoaded()){
            ClassBuilder classBuilder = new ClassBuilder("resources", "R", "src/resources/R.java");
            classBuilder.generateClass();
        }else{
            System.out.println(resourcesLoader.getErrorMessage());
        }

    }
}
