package inevaup.resources;

//Json Simple dependency: https://cliftonlabs.github.io/json-simple/target/json-simple-3.1.1.jar

public class Main {
    
    public static void main(String[] args) {

        //Run this class to autogenerated the R class
        
        AppResources appResources = AppResources.getAppResources();
        appResources.loadResources();

        if(appResources.AreAllResourcesLoaded()){
            ClassBuilder classBuilder = new ClassBuilder("resources", "R", "src/resources/R.java");
            classBuilder.generateClass();
        }else{
            System.out.println(appResources.getErrorMessage());
        }

    }
}
