
package mainmenu;

import resources.ResourcesLoader;

public class Main {
    
    public static void main(String[] args) {

        //Run this class to autogenerated the R class
        
        ResourcesLoader resourcesLoader = new ResourcesLoader();
        resourcesLoader.loadResources();

        if(resourcesLoader.AreAllResourcesLoaded()){
            MainMenuInterface mainMenuInterface = new MainMenuInterface();
            mainMenuInterface.setVisible(true);
        }else{
            System.out.println(resourcesLoader.getErrorMessage());
        }

    }
}
